version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-nzyme}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nzyme_password}
      - POSTGRES_DB=${POSTGRES_DB:-nzyme}
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - nzyme_postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5433}:5432"  # Exposed for manual nzyme setup
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-nzyme}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Note: nzyme-node requires manual setup due to image limitations
  # The r4ulcl/nzyme image uses an outdated version (v1.2.2 from 2021)
  # For production use, consider:
  # 1. Building your own Docker image with nzyme v2.0+
  # 2. Installing nzyme directly on the host system
  # 3. Using the official installation guide at https://docs.nzyme.org/

  # Placeholder web server to show installation instructions
  setup-instructions:
    image: nginx:alpine
    volumes:
      - ./nzyme-instructions.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "${NZYME_PORT:-22900}:80"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  nzyme_postgres_data:
  nzyme_config:
  nzyme_data:
  nzyme_logs:
  nzyme_tap_config:
  nzyme_tap_data:
  nzyme_tap_logs:

x-ontree:
  subdomain: nzyme
  host_port: 22900
  is_exposed: false
  tailscale_exposed: false
  emoji: "🛡️"
  bypass_security: false
  requires_https: true
  description: "Network Defense System for WiFi and Ethernet monitoring"
  notes: |
    nzyme is a network defense system that monitors WiFi and Ethernet networks.

    Note: The tap component has limited functionality in containers due to security
    restrictions. For full network monitoring capabilities, consider running
    nzyme-tap on dedicated hardware with appropriate network permissions.

    Default credentials:
    - Username: admin
    - Password: Set via NZYME_ADMIN_PASSWORD environment variable

    After installation:
    1. Access the web interface at https://nzyme.yourdomain.com
    2. Complete the initial setup wizard
    3. Generate a leader secret for connecting taps
    4. Configure network monitoring as needed