run:
  build-tags:
    - integration
  tests: true
linters:
  enable:
    - gosec
    - unused
    - errcheck
    - revive
    - govet
    - staticcheck
    - ineffassign
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    severity: medium
    confidence: medium
  revive:
    severity: warning
    enable-all-rules: false
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: var-declaration
      - name: var-naming

issues:
  exclude-rules:
    - linters:
        - errcheck
        - gosec
      path: _test\.go
    - linters:
        - govet
      text: 'shadow: declaration of "err" shadows declaration'
    - linters:
        - govet
      path: main\.go
      text: exitAfterDefer
    - linters:
        - gosec
      path: internal/docker/apps\.go
      text: G304
    - linters:
        - gosec
      path: internal/server/handlers\.go
      text: G304
    - linters:
        - gosec
      path: internal/server/handlers\.go
      text: G306
    - linters:
        - gosec
      path: internal/yamlutil/yamlutil\.go
      text: G306
    - linters:
        - gosec
      path: cmd/treeos/main\.go
      text: G302
    - linters:
        - gosec
      path: cmd/treeos/main\.go
      text: G204
    - linters:
        - gosec
      path: internal/ollama/worker\.go
      text: G204
    - linters:
        - gosec
      path: internal/server/handlers_models\.go
      text: G204
    - linters:
        - gosec
      path: internal/server/handlers_logging\.go
      text: G107
    - linters:
        - typecheck
      path: internal/migrations/migrations\.go
      text: 'pattern .*: no matching files found'
    - linters:
        - staticcheck
      text: 'ST1005: error strings should not be capitalized'
    - linters:
        - errcheck
      text: 'Error return value of `.*\.Close` is not checked'
    - linters:
        - errcheck
      text: 'Error return value of `w\.Write` is not checked'
    - linters:
        - errcheck
      text: 'Error return value of `s\.caddyClient\.DeleteRoute` is not checked'
    - linters:
        - errcheck
      path: internal/server/handlers\.go
      text: 'Error return value of `s\.dockerClient\.GetAppDetails` is not checked'
    - linters:
        - errcheck
      path: internal/server/api_handlers_chat\.go
      text: 'Error return value of `.*\.Encode` is not checked'
    - linters:
        - errcheck
      path: internal/server/api_handlers_status\.go
      text: 'Error return value of `json\.NewEncoder\(w\)\.Encode` is not checked'
    - linters:
        - errcheck
      path: internal/server/api_handlers_status\.go
      text: 'Error return value of `\(\*encoding/json\.Encoder\)\.Encode` is not checked'
    - linters:
        - errcheck
      path: internal/server/handlers_logging\.go
      text: 'Error return value of `.*\.Encode` is not checked'
    - linters:
        - errcheck
      path: internal/server/handlers_logging\.go
      text: 'Error return value of `file\.WriteString` is not checked'
    - linters:
        - errcheck
      path: internal/server/handlers_logging\.go
      text: 'Error return value of `io\.Copy` is not checked'
    - linters:
        - errcheck
      path: internal/server/handlers_logging\.go
      text: 'Error return value of `fmt\.Sscanf` is not checked'
    - linters:
        - errcheck
      path: internal/server/handlers_models\.go
      text: 'Error return value of `.*\.Encode` is not checked'
    - linters:
        - errcheck
      path: internal/ollama/worker\.go
      text: 'Error return value of `cmd\.Wait` is not checked'
    - linters:
        - gosec
      path: internal/database/database\.go
      text: 'G201: SQL string formatting'
    - linters:
        - staticcheck
      path: internal/docker/container_naming_test\.go
      text: 'SA1019: types.Container is deprecated'
    - linters:
        - revive
      path: internal/update/types\.go
      text: 'exported: type name will be used as update\.'
  max-issues-per-linter: 0
  max-same-issues: 0
