# GoReleaser configuration for OnTree
# This file configures the release process for multi-architecture builds
#
# NOTE: macOS builds are handled separately in .github/workflows/release-macos.yml
# due to CGO requirements for SQLite (github.com/mattn/go-sqlite3).
# Cross-compiling CGO code from Linux to macOS requires the macOS SDK,
# so we use native macOS runners instead.
version: 2

project_name: treeos


before:
  hooks:
    # Ensure go modules are downloaded
    - go mod download

builds:
  - id: treeos-amd64
    main: ./cmd/treeos
    binary: treeos
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X {{.ModulePath}}/internal/version.Version={{.Version}}
      - -X {{.ModulePath}}/internal/version.Commit={{.Commit}}
      - -X {{.ModulePath}}/internal/version.BuildDate={{.Date}}
  
  - id: treeos-darwin-arm64
    main: ./cmd/treeos
    binary: treeos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X {{.ModulePath}}/internal/version.Version={{.Version}}
      - -X {{.ModulePath}}/internal/version.Commit={{.Commit}}
      - -X {{.ModulePath}}/internal/version.BuildDate={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Include setup files with the binary
    files:
      - src: .claude/commands/treeos-setup-production-noconfirm.sh
        dst: setup-production.sh
      - src: init/systemd/treeos.service
        dst: treeos.service
      - src: init/launchd/com.ontree.treeos.plist
        dst: com.ontree.treeos.plist
      - src: README.setup.md
        dst: README.md
        info:
          mode: 0644

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Other Changes
      order: 999

release:
  # GitHub repository configuration
  # These will be set via environment variables in the CI pipeline
  # For local testing, the release step is skipped in snapshot mode
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  mode: replace
  replace_existing_artifacts: true
  footer: |
    ## Installation

    Download the appropriate package for your platform from the assets below.

    ### Supported Platforms
    - **Linux AMD64** (x86_64) - Intel/AMD processors
    - **macOS ARM64** (Apple Silicon) - M1/M2/M3 chips

    ### Quick Start (Demo Mode)
    ```bash
    # Extract the package
    tar -xzf treeos_{{ .Version }}_<platform>.tar.gz
    cd treeos_{{ .Version }}_<platform>

    # Run in demo mode (uses local directories)
    ./treeos --demo
    ```

    ### Production Installation
    ```bash
    # Extract the package
    tar -xzf treeos_{{ .Version }}_<platform>.tar.gz
    cd treeos_{{ .Version }}_<platform>

    # Run the setup script (requires sudo)
    sudo ./setup-production.sh
    ```

    The setup script will:
    - Create the `ontree` user
    - Set up directories at `/opt/ontree`
    - Install the binary
    - Configure automatic startup via systemd (Linux) or launchd (macOS)

    See the included README.md for detailed instructions.