version: '3.8'

services:
  librechat:
    image: ghcr.io/danny-avila/librechat-dev:latest
    container_name: ${COMPOSE_PROJECT_NAME}-librechat-1
    restart: unless-stopped
    ports:
      - "${PORT:-3080}:3080"
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_KEY=${MEILI_KEY:-changeme}
      - SEARCH=true
      - OLLAMA_BASE_URL=http://host.containers.internal:11434
      - JWT_SECRET=${JWT_SECRET:-change-me-jwt}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-change-me-refresh}
      - SESSION_SECRET=${SESSION_SECRET:-change-me-session}
      - ALLOW_SIGNUP=${ALLOW_SIGNUP:-true}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-true}
    volumes:
      - ./shared/config/librechat.yaml:/app/librechat.yaml:ro
      - librechat_images:/app/client/public/images
      - librechat_logs:/app/api/logs
    depends_on:
      - mongodb
      - meilisearch
    extra_hosts:
      - "host.containers.internal:host-gateway"

  mongodb:
    image: mongo:latest
    container_name: ${COMPOSE_PROJECT_NAME}-mongodb-1
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    command: --noauth

  meilisearch:
    image: getmeili/meilisearch:v1.12.3
    container_name: ${COMPOSE_PROJECT_NAME}-meilisearch-1
    restart: unless-stopped
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_KEY=${MEILI_KEY:-changeme}
    volumes:
      - meilisearch_data:/meili_data

x-ontree:
  subdomain: ${APP_SUBDOMAIN:-librechat}
  host_port: 3080
  is_exposed: false
volumes:
  librechat_images:
  librechat_logs:
  mongodb_data:
  meilisearch_data:
