version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - {{SHARED_OLLAMA_PATH}}:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    labels:
      - "ontree.inference=true"
      - "ontree.type=ollama"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]