version: '3.8'

services:
  ollama:
    image: ollama/ollama:rocm
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - {{SHARED_MODELS_PATH}}:/root/.ollama
    labels:
      - "ontree.inference=true"
      - "ontree.type=ollama"
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0