version: '3.8'

services:
  ollama:
    image: docker.io/ollama/ollama:rocm
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - {{SHARED_OLLAMA_PATH}}:/root/.ollama
    labels:
      - "ontree.inference=true"
      - "ontree.type=ollama"
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - "44"    # video
      - "991"   # render
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.5.1
      - OLLAMA_HOST=0.0.0.0