version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "3001:8080"
    volumes:
      - {{ONTREE_APPS_PATH}}/apps/{{APP_NAME}}/volumes/openwebui_data:/app/backend/data
      - {{SHARED_OLLAMA_PATH}}:/models:ro
    extra_hosts:
      - "host.containers.internal:host-gateway"
    environment:
      - OLLAMA_BASE_URL=http://host.containers.internal:11434
