version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - openwebui_data:/app/backend/data
    ports:
      - "8080:8080"
    environment:
      - WEBUI_SECRET_KEY=change-me-to-random-string
    restart: unless-stopped

volumes:
  openwebui_data: