version: '3.8'
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:ollama
    restart: unless-stopped
    ports:
      - "4000:8080"
    volumes:
      - openwebui_data:/app/backend/data
      - ollama_data:/root/.ollama
    # OpenWebUI environment variables
    # You can customize these as needed
    # Uncomment and modify the environment section if needed:
    # environment:
    #   OLLAMA_API_BASE_URL: http://localhost:11434/api

volumes:
  openwebui_data:
  ollama_data: