version: '3.8'

services:
  ollama:
    image: ollama/ollama:rocm  # AMD ROCm optimized image
    container_name: ollama-amd
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - "44"    # video group
      - "993"   # render group
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.5.1  # For gfx1151 GPU
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    ports:
      - "11434:11434"
    networks:
      - ollama-network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - open-webui_data:/app/backend/data
    ports:
      - "4000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your-secret-key-here  # Change this!
      - WEBUI_AUTH=true  # Set to false if you don't want authentication
    depends_on:
      - ollama
    networks:
      - ollama-network

volumes:
  ollama_data:
  open-webui_data:

networks:
  ollama-network:
    driver: bridge