version: "3.8"

services:
  mongo:
    image: mongo:6.0.15
    volumes:
      - unifi_mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  app:
    image: lscr.io/linuxserver/unifi-network-application:8.4.62
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - MONGO_USER=
      - MONGO_PASS=
      - MONGO_DBNAME=${MONGO_DBNAME:-unifi}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - unifi_config:/config
      - ./fix-mongo-uri.sh:/custom-cont-init.d/fix-mongo-uri.sh:ro
    ports:
      - "${UNIFI_HTTPS_PORT:-8443}:8443"
      - "${UNIFI_HTTP_PORT:-8080}:8080"
      - "${UNIFI_STUN_PORT:-3478}:3478/udp"
      - "${UNIFI_DISCOVERY_PORT:-10001}:10001/udp"
      - "${UNIFI_L2_DISCOVERY_PORT:-1900}:1900/udp"
      - "${UNIFI_SPEEDTEST_PORT:-6789}:6789"
      - "${UNIFI_SYSLOG_PORT:-5514}:5514/udp"
    restart: unless-stopped

volumes:
  unifi_mongo_data:
  unifi_config:

x-ontree:
  subdomain: unifi
  host_port: 8443
  is_exposed: false
  tailscale_exposed: false
  emoji: "🌐"
  bypass_security: false