# Pull Request Pipeline - Runs essential checks on PRs
when:
  event: pull_request

steps:
  # Quick syntax and format checks
  - name: quick-checks
    image: golang:1.22
    commands:
      - make deps
      - make check-templates
    environment:
      GOCACHE: /tmp/go-build-cache
      GOMODCACHE: /tmp/go-mod-cache
    volumes:
      - /tmp:/tmp

  # Run linting
  - name: lint
    image: golangci/golangci-lint:v1.64.7
    commands:
      - make deps
      - make embed-assets
      - golangci-lint run --timeout=5m
    environment:
      GOCACHE: /tmp/go-build-cache
      GOMODCACHE: /tmp/go-mod-cache
    volumes:
      - /tmp:/tmp

  # Run unit tests
  - name: test
    image: golang:1.22
    commands:
      - make deps
      - make embed-assets
      - make test
    environment:
      GOCACHE: /tmp/go-build-cache
      GOMODCACHE: /tmp/go-mod-cache
    volumes:
      - /tmp:/tmp

  # Build verification
  - name: build
    image: golang:1.22
    commands:
      - make deps
      - make embed-assets
      - make build
    environment:
      GOCACHE: /tmp/go-build-cache
      GOMODCACHE: /tmp/go-mod-cache
    volumes:
      - /tmp:/tmp

  # Documentation typecheck
  - name: docs-typecheck
    image: node:20-alpine
    commands:
      - cd documentation
      - npm install --no-audit
      - npm run typecheck
    environment:
      CI: "true"