# Test Pipeline - Runs on all pushes and pull requests
when:
  event: [push, pull_request]
  branch: [main, develop, release/*]

steps:
  # Get Go version from go.mod
  - name: detect-go-version
    image: alpine:latest
    commands:
      - GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
      - echo "GO_VERSION=$GO_VERSION" > /tmp/go-version.env
    volumes:
      - /tmp:/tmp

  # Unit tests
  - name: test-unit
    image: golang:1.22
    commands:
      - source /tmp/go-version.env
      - make deps
      - make check-templates
      - make embed-assets
      - make test
      - make test-race
    volumes:
      - /tmp:/tmp
    environment:
      GOCACHE: /tmp/go-build-cache
      GOMODCACHE: /tmp/go-mod-cache

  # Upload coverage to codecov
  - name: coverage
    image: codecov/codecov:latest
    commands:
      - codecov upload-process --disable-search --fail-on-error -f ./coverage.out --flags unittests --name codecov-umbrella
    secrets: [codecov_token]
    when:
      event: push

  # Linting
  - name: lint
    image: golangci/golangci-lint:v1.64.7
    commands:
      - source /tmp/go-version.env
      - make deps
      - make check-templates
      - make embed-assets
      - golangci-lint run --timeout=5m
    volumes:
      - /tmp:/tmp
    environment:
      GOCACHE: /tmp/go-build-cache
      GOMODCACHE: /tmp/go-mod-cache

  # Build verification
  - name: build
    image: golang:1.22
    commands:
      - source /tmp/go-version.env
      - make deps
      - make check-templates
      - make build
    volumes:
      - /tmp:/tmp
    environment:
      GOCACHE: /tmp/go-build-cache
      GOMODCACHE: /tmp/go-mod-cache

  # E2E tests
  - name: e2e-tests
    image: mcr.microsoft.com/playwright:v1.48.0-focal
    commands:
      - source /tmp/go-version.env
      # Install Go for building the app
      - apt-get update && apt-get install -y wget
      - wget -q https://go.dev/dl/go1.22.0.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go1.22.0.linux-amd64.tar.gz
      - export PATH=$PATH:/usr/local/go/bin
      # Build and test
      - make deps
      - cd tests/e2e
      - npm ci
      - npx playwright install --with-deps chromium
      - cd ../..
      - make test-e2e
    volumes:
      - /tmp:/tmp
    environment:
      CI: "true"
      GOCACHE: /tmp/go-build-cache
      GOMODCACHE: /tmp/go-mod-cache
    when:
      event: push

  # Documentation build and typecheck
  - name: docs-build
    image: node:20-alpine
    commands:
      - cd documentation
      - npm install --no-audit
      - npm run typecheck
      - npm run build
    environment:
      CI: "true"
      NODE_ENV: production
    when:
      event: push

  # Check for broken links in documentation
  - name: docs-check-links
    image: node:20-alpine
    commands:
      - cd documentation
      - if [ -d "build" ]; then
      -   echo "Checking for broken internal links..."
      -   find build -name "*.html" -exec grep -l 'href="/404"' {} \; | head -20 || true
      - fi
    when:
      event: push
      depends_on: [docs-build]